### PR TITLE
Add reducer&actions

### PR DESCRIPTION
**Pull request by mrkamin**
What does this PR do?
This PR is raised to submit for code review in the Microvers dashboard of Mohammad Rafi Amin.

Description of the task to be completed 👎

I will be building my "BookStore" website for more than a whole week. below are the tasks that will be done.

Project 1: Initialize the project with components (React only).
**Project 2: Add reducers and actions.**
Project 3: Use Redux in React components.
Project 4: Connect to API.
Project 5: Styling.

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @mrkamin, kindly add the future features section to your readme 👍🏿

**Comment by mrkamin** [comment]
> Hi @mrkamin, kindly add the future features section to your readme 👍🏿

Hi, @prolajumokeoni thanks for your message kindly could you please explain more details? sorry I couldn't get your Idea.

**Comment by prolajumokeoni** [comment]
HI @mrkamin, you are missing the [ future features](https://github.com/microverseinc/readme-template#-future-features-) section in your readme please add it, check the [readme template](https://github.com/microverseinc/readme-template#-future-features-) all sections from the template should be in your readme  👍🏿

**Comment by mrkamin** [comment]
> Hi @mrkamin, kindly add the future features section to your readme 👍🏿

Hi, @prolajumokeoni, I did some changes in README and Update it, hope I have done the right.

**Comment by mrkamin** [comment]
> HI @mrkamin, you are missing the [ future features](https://github.com/microverseinc/readme-template#-future-features-) section in your readme please add it, check the [readme template](https://github.com/microverseinc/readme-template#-future-features-) all sections from the template should be in your readme 👍🏿

Hi, @prolajumokeoni, thanks for your feedback, I applied your valuable feedback, kindly could you please see it again?

**Comment by prolajumokeoni** [comment]
Your readme has all sections, Good job 👍🏿

**Review by prolajumokeoni — APPROVED** [review]
Hi @mrkamin 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights

 - Installed and used  Redux Toolkit 👍🏿
- Created  book's actions and reducer ✅  


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mrkamin** [comment]
> Hi @mrkamin
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉
> 
> ## Highlights
> * Installed and used  Redux Toolkit 👍🏿
> * Created  book's actions and reducer ✅
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> You can also consider:
> 
> * N/A
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Hi, @prolajumokeoni
thanks for your valuable feedback

**Review by emmanuellekamwa — APPROVED** [review]
**STATUS: APPROVED 🍾✔🎉**
Hello @mrkamin 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- You asked for the changes in a polite and friendly way.
- Your linters are passing all the checks.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

@emmanuellekamwa 
thanks for your good and valuable feedback.

**Pull request merged**
